# Generated by Django 2.1.1 on 2018-09-30 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name or title of lost object', max_length=200)),
                ('type_of_object', models.CharField(help_text='What type of object are you posting', max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('location_found', models.CharField(help_text='Where did you find the object?', max_length=200)),
                ('pickup_details', models.CharField(help_text='Details of pickup location', max_length=200)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('PU', 'Picked Up')], max_length=12)),
                ('image', models.ImageField(upload_to='img/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
