# Generated by Django 2.1.1 on 2018-09-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_auto_20180930_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location_found',
            field=models.TextField(help_text='Where did you find the object?', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='pickup_details',
            field=models.TextField(help_text='Details of pickup location', max_length=300),
        ),
    ]
